### ISSUE TITLE
Check UpdateAlertStatus GRPC function

### ISSUE THREAD

**Issue by CanuckMarc** [NubeIO/lib-module-go#26]
@enjuthulung  can you please check the operation of the `UpdateAlertStatus` grpc function in this library.  It doesn't seem to work when i'm calling it from RQL (see example below).  I am getting a `record not found` error. 

https://github.com/NubeIO/lib-module-go/blob/9b5beeb17bc1578d8b6d9f0e54669762823387b4/nmodule/implalerts.go#L53-L65

```
function closeAlert(hostUUID, alertUUID) {
  try {
    const body = {
      Status: "closed",
    };
    const opts = {
      Args: {},
      HostUUID: hostUUID,  // this is the server host uuid (where the RQL rule is running).
    };
    return RQL.ROS.UpdateAlertStatus(alertUUID, body, opts);  // This calls the grpc function linked above
  } catch (error) {
    throw error;
  }
}
```

**Comment by enjuthulung** [comment]
@CanuckMarc moved to jira.

**Comment by CanuckMarc** [comment]
https://github.com/NubeIO/rubix-os/pull/945
